### ISSUE TITLE
Exception trapped:'key offset not found in dict'

### ISSUE THREAD

**Issue by roussell** [jh71283/IndigoMQTTBridge#3]
Not sure if this is an actual issue or a problem with my config but I thought it worth raising. I'm using a Sonoff Basic flashed with Tasmota 6.3.0. To that I've added a 1-wire DS18B20 temperature sensor. The MQTT topic is: `house/sonoff-boat/tele/SENSOR` and publishes the following payload:

`{"Time":"2018-12-06T14:32:19","DS18B20":{"Temperature":44.3},"TempUnit":"F"}`

I'm trying to use the new Payload Extraction feature and from the readme have deduced that I need the following: `DS18B20->Temperature`. I set the Unit field to 'F' (no quotes) but otherwise left the config fields as-is (blank Formula and Offset, Precision profiled with 1).

The error I see in the indigo log is `Exception trapped:'key offset not found in dict'` and enabling debug gives no further info, other than displaying the payload (above) just before the error. Attached is a screenshot of the config, and error.

I should add that I seem to have no problem with mqtt switches setup in Indigo using this plugin, including this particular Sonoff device, and that the temp sensor reports correctly in hassio.

Terry

![screen shot 2018-12-06 at 7 33 09 am](https://user-images.githubusercontent.com/3043951/49589470-1c659a80-f92f-11e8-8310-9f754bed215c.png)

**Comment by HackintoshMan** [comment]
@roussell The data extraction was a feature I worked on. Let me take a look and see if there is something I overlooked.

**Comment by AaronLionsheep** [comment]
@roussell I've had the MQTT Sensor device running for a few weeks now (as well as the MQTT Weather Sensor) and have not seen this issue before. Can you try putting a `0` in for the offset?

**Comment by jh71283** [comment]
@HackintoshMan I think it might be pre-existing devices that don't have the offset property that are causing this. Might need to detect and initialise, or maybe we need a 'upgrade' step for old devices?

**Comment by AaronLionsheep** [comment]
@roussell I think that's what is happening. I thought I had some logic in place to detect this (hence the default of 0), but it seems it is not catching it for older devices. I think if you hit Save or put in a 0 for offset then it should fix that specific device.

**Comment by roussell** [comment]
What ended up working was deleting the device and recreating it using a different name. The first time I recreated it using the same name as the previous non-working device I had the same error. Once I recreated it using a different name, with a blank Payload Extraction field - I got an error which was "Unable to extract data using path '' which was promising. After editing the new device with the Payload extraction keys, it starting working perfectly. One thing I did notice, which I'll file as a separate issue was that I upgraded the mosquito broker and it no longer accepts certain characters in the client ID, namely the '/' in the default paho client.py which is currently set to "paho/"+random string". I did a hard change in the client.py to "Indigo-" to allow it to connect to the broker.

**Comment by AaronLionsheep** [comment]
@roussell 
> with a blank Payload Extraction field - I got an error which was "Unable to extract data using path '' which was promising

Actually that is not the expected behavior. When the payload extraction field is blank, it should take the value right from the payload. Some devices might emit their raw temperature over a topic. it looks like it is not recognizing that the extraction field is blank.

I'll see if I can recreate some of your issues once I'm done with my final exams this week.

**Comment by kanutten** [comment]
@HackintoshMan 
Thanks for a great plugin. Thats the missing link in indigo, a good mqqt client :)
I have some issues

> Actually that is not the expected behavior. When the payload extraction field is blank, it should take the value right from the payload. Some devices might emit their raw temperature over a topic. it looks like it is not recognizing that the extraction field is blank.

I have the same issue. when it sends over a topic its not working. 
Its working fine with 4.0

I also have alot of these In my log, every time a device is updated it prints to the log. And when its updated every second my logg is flooded.
` GreenSky MQTT Bridge            new device 1 set to 6557.0
   GreenSky MQTT Bridge            new device 1 set to 6559.0
   GreenSky MQTT Bridge            new device 1 set to 6573.0
   GreenSky MQTT Bridge            new device 1 set to 6579.0
   GreenSky MQTT Bridge            new device 1 set to 6570.0`

In V4.0 these was hidden, in 4.2 its not. is it possible to make it optional to print to log?.
